Fix multiple spelling mistakes
cesium/fractal-tree pull request #7
Opened 2019-08-20 13:47 UTC by ggoncalopereira

Attempt fix a bunch of spelling mistakes.
Couldn't test locally for any discrepancies (HTML ellipsis, apostrophes, quotes...) but I'll have to trust my gut on this one.

2019-08-20 13:48 UTC, ggoncalopereira commented
Also had to guess the meaning of some sentences, but hopefully the main essence of it is still present.

2019-08-20 14:06 UTC, nelsonmestevao requested changes
We don't edit the `HTML` files directly. They are automatically generated from [hugo](https://gohugo.io/).

The source code for the website tutorial is found under [`src/`](https://github.com/cesium/fractal-tree/tree/master/src) and I believe the file you are looking for is [`_index.md`](https://github.com/cesium/fractal-tree/blob/master/src/content/_index.md).

2019-08-20 14:08 UTC, nelsonmestevao commented
@ggoncalopereira can you drop the first commit? :pray:

2019-08-20 14:10 UTC, ggoncalopereira commented
@nelsonmestevao my bad - updated the .md and only pushed the .HTML commit. Should be fixed soon

2019-08-20 14:24 UTC, ggoncalopereira commented
LGTM, should hopefully be good to go @nelsonmestevao

2019-08-20 14:31 UTC, nelsonmestevao requested changes

2019-08-20 14:31 UTC, nelsonmestevao commented on src/content/_index.md
> +tree as it is being created. Okay, after this basic explanation let&rsquo;s get it
Use `'` here, please :pray:

2019-08-20 14:31 UTC, nelsonmestevao commented on src/content/_index.md
> +Since a blank canvas is boring and programming is not, you need to give it a
Remove the extra space :pray:

2019-08-20 14:31 UTC, nelsonmestevao commented on src/content/_index.md
> +job by connecting those points. See? As easy as it can be. See more [`here`](https://p5js.org/reference/#/p5/line)
Please, try to keep the text under 80 characters :point_up:

2019-08-20 14:31 UTC, nelsonmestevao commented on src/content/_index.md
> +ck to interfere with the left side. Instead it goes right and builds the
`ck` should be `back`

2019-08-20 14:49 UTC, ggoncalopereira commented
Latest commit should fix all those issues - also pushed back previous wrongly indented sentences to keep the margin of 80 characters, max.

2019-08-20 15:02 UTC, ggoncalopereira commented
Actually - one second, found a bunch more things...

2019-08-20 15:09 UTC, ggoncalopereira commented
Should be good now!

2019-08-20 15:24 UTC, ggoncalopereira commented
Should be good now!

2019-09-23 14:23 UTC, ggoncalopereira commented
@nelsonmestevao any updates on this? Pinging to ask, that way the repo can be deployed and/or used whenever

2019-09-23 14:38 UTC, nelsonmestevao commented
I am coming back to this asap :muscle:

2019-12-08 16:39 UTC, merged